# Generated by Django 2.2.5 on 2019-09-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdata',
            name='published_date',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='source',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogdata',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
