# Generated by Django 2.2.5 on 2019-09-12 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0002_auto_20190910_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=400)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('nickname', models.CharField(default='anonymous', max_length=50)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='parsed_data.BlogData')),
            ],
        ),
    ]
