# Generated by Django 2.2.5 on 2019-09-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsed_data', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
